### ISSUE TITLE
Probleme mit Job pull-and-run-blogpost-checker-image

### ISSUE THREAD

**Issue by MBoegers** [adessoSE/devblog#242]
Es sieht so aus als hätten PR #241 und #233  dasselbe Problem in den Checks. 
Der Job [pull-and-run-blogpost-checker-image](https://github.com/adessoSE/devblog/runs/6520817400?check_suite_focus=true) scheint nicht den richtigen Commit zu nehmen. 
Bei beiden MRs ist es [4ff65608dd4d37db6231b7e33fa7f855d148ac91](https://github.com/adessoSE/devblog/commit/4ff65608dd4d37db6231b7e33fa7f855d148ac91).

**Comment by jo2** [comment]
Das Problem ist behoben, der Stand des Hauptrepos in den Branches war nicht aktuell. Um das Problem zu beheben muss `adessoSE:master` in den Branch mit dem Artikel gemergt werden. Für die beiden genannten PRs habe ich das schon gemacht. Ich schließe daher den Issue. /close
